In [7]:
import subprocess
import os
import numpy as np
import pandas as pd

#importam datasetul nostru
input_file = "Dataset.csv"

#citim din csv si punem in data
data = pd.read_csv(input_file, header = 0)
data.head()

No.  Country        Date  Confirmed  Death  newConfirmed  newDeath
0    1  Romania  2019-12-31          0      0             0         0
1    2  Romania  2020-01-01          0      0             0         0
2    3  Romania  2020-01-02          0      0             0         0
3    4  Romania  2020-01-03          0      0             0         0
4    5  Romania  2020-01-04          0      0             0         0

In [8]:
#Stergem coloana cu numarul deoarece nu avem nevoie de ele in prelucrarea datelor
data = data.drop(data.columns[0], axis=1)
data

Country        Date  Confirmed  Death  newConfirmed  newDeath
0    Romania  2019-12-31          0      0             0         0
1    Romania  2020-01-01          0      0             0         0
2    Romania  2020-01-02          0      0             0         0
3    Romania  2020-01-03          0      0             0         0
4    Romania  2020-01-04          0      0             0         0
..       ...         ...        ...    ...           ...       ...
116  Romania  2020-04-25      10635    601           218        34
117  Romania  2020-04-26      11036    619           401        18
118  Romania  2020-04-27      11339    641           303        22
119  Romania  2020-04-28      11616    663           277        22
120  Romania  2020-04-29      11978    693           362        30

[121 rows x 6 columns]

In [9]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

#folosim un label encoder pentru coloanele country si date pentru a le putea transforma in valori numerice
le = preprocessing.LabelEncoder()

le.fit(data['Date'])
data.loc[:, 'Date'] = le.transform(data['Date'])

le.fit(data['Country'])
data.loc[:, 'Country'] = le.transform(data['Country'])

#punem in y doar Country si Date
y = data.drop(data.columns[2], axis=1)
y = y.drop(y.columns[2], axis=1)
y = y.drop(y.columns[2], axis=1)
y = y.drop(y.columns[2], axis=1)

#In X_final punem restul coloanelor
X_final = data.drop(data.columns[1], axis=1)
X_final = X_final.drop(X_final.columns[0], axis=1)

y_train, y_test, X_train, X_test = train_test_split(X_final, y, test_size=0.17)

In [10]:
#X_train contine datele de train pentru input
X_train

Country  Date
24         0    24
103        0   103
93         0    93
67         0    67
92         0    92
..       ...   ...
91         0    91
109        0   109
29         0    29
13         0    13
23         0    23

[100 rows x 2 columns]

In [11]:
#y_train contine datele de train pentru rezultatul inputului
y_train

Confirmed  Death  newConfirmed  newDeath
24           0      0             0         0
103       6300    316           310        25
93        2738    115           278        23
67           9      0             0         0
92        2460     92           215        10
..         ...    ...           ...       ...
91        2245     82           136        17
109       8418    421           351        10
29           0      0             0         0
13           0      0             0         0
23           0      0             0         0

[100 rows x 4 columns]

In [13]:
#X_test contine datele de input pentru test
X_test

Country  Date
42         0    42
41         0    41
120        0   120
104        0   104
44         0    44
65         0    65
100        0   100
80         0    80
61         0    61
57         0    57
114        0   114
111        0   111
96         0    96
59         0    59
18         0    18
69         0    69
101        0   101
50         0    50
60         0    60
106        0   106
56         0    56

In [14]:
#y_test contine datele rezultate in urma inputului de test
y_test

Confirmed  Death  newConfirmed  newDeath
42           0      0             0         0
41           0      0             0         0
120      11978    693           362        30
104       6633    331           333        15
44           0      0             0         0
65           6      0             2         0
100       5202    248           441        28
80         308      0            31         0
61           3      0             0         0
57           1      0             1         0
114      10096    545           386        21
111       8936    478           190        27
96        3864    151           251         5
59           3      0             2         0
18           0      0             0         0
69          15      0             0         0
101       5467    270           265        22
50           0      0             0         0
60           3      0             0         0
106       7216    372           337        21
56           0      0             0         0

In [15]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score

#folosim MLP regressor pentru predictii
#MLP Regressor pentru NN Multy Layer
regr = MLPRegressor(solver='adam', hidden_layer_sizes=(200,100), max_iter=10000, verbose = 'true',activation='relu')

#Antrenam modelul folosind setul de train
regr.fit(X_train, y_train)

#Facem predictii folosind setul de test
y_pred = regr.predict(X_test)

Iteration 1, loss = 1629562.58131070
Iteration 2, loss = 1627091.64381731
Iteration 3, loss = 1624746.44726566
Iteration 4, loss = 1622467.12566039
Iteration 5, loss = 1620293.71059235
Iteration 6, loss = 1618206.18970531
Iteration 7, loss = 1616158.12425028
Iteration 8, loss = 1614203.74674996
Iteration 9, loss = 1612371.19920041
Iteration 10, loss = 1610520.11010393
Iteration 11, loss = 1608698.84635024
Iteration 12, loss = 1606851.62171183
Iteration 13, loss = 1604978.90241679
Iteration 14, loss = 1603062.65483693
Iteration 15, loss = 1601116.97117584
Iteration 16, loss = 1599122.52354803
Iteration 17, loss = 1597088.39384224
Iteration 18, loss = 1595072.56372661
Iteration 19, loss = 1593034.42270442
Iteration 20, loss = 1590935.26651745
Iteration 21, loss = 1588773.09775785
Iteration 22, loss = 1586554.90362232
Iteration 23, loss = 1584249.10001885
Iteration 24, loss = 1581881.82228096
Iteration 25, loss = 1579440.64973472
Iteration 26, loss = 1576922.77422349
Iteration 27, loss = 

Iteration 320, loss = 713168.08143520
Iteration 321, loss = 712861.09618828
Iteration 322, loss = 712552.36196271
Iteration 323, loss = 712243.34947549
Iteration 324, loss = 711933.48607693
Iteration 325, loss = 711621.47113622
Iteration 326, loss = 711308.13040809
Iteration 327, loss = 710993.21074177
Iteration 328, loss = 710677.27521057
Iteration 329, loss = 710359.88060525
Iteration 330, loss = 710041.42380698
Iteration 331, loss = 709721.67852490
Iteration 332, loss = 709400.25021527
Iteration 333, loss = 709077.45271713
Iteration 334, loss = 708753.41333368
Iteration 335, loss = 708427.87901191
Iteration 336, loss = 708101.71187301
Iteration 337, loss = 707773.79286627
Iteration 338, loss = 707444.72385574
Iteration 339, loss = 707113.49517166
Iteration 340, loss = 706781.31913502
Iteration 341, loss = 706448.26712387
Iteration 342, loss = 706113.32563909
Iteration 343, loss = 705776.55776790
Iteration 344, loss = 705438.86646661
Iteration 345, loss = 705100.02172456
Iteration 34

Iteration 649, loss = 561089.94258265
Iteration 650, loss = 560627.63203511
Iteration 651, loss = 560168.15296756
Iteration 652, loss = 559710.96379270
Iteration 653, loss = 559247.54746097
Iteration 654, loss = 558790.32311771
Iteration 655, loss = 558330.75644242
Iteration 656, loss = 557872.81757042
Iteration 657, loss = 557415.67022620
Iteration 658, loss = 556972.31464498
Iteration 659, loss = 556536.74988673
Iteration 660, loss = 556103.53891547
Iteration 661, loss = 555614.30932295
Iteration 662, loss = 555162.58381396
Iteration 663, loss = 554739.00001695
Iteration 664, loss = 554308.35079671
Iteration 665, loss = 553894.36788692
Iteration 666, loss = 553428.69663413
Iteration 667, loss = 553009.21250454
Iteration 668, loss = 552540.79315485
Iteration 669, loss = 552191.43884693
Iteration 670, loss = 551785.93670651
Iteration 671, loss = 551293.71212574
Iteration 672, loss = 550943.82263483
Iteration 673, loss = 550463.16087218
Iteration 674, loss = 550114.48265878
Iteration 67

Iteration 950, loss = 488599.64637427
Iteration 951, loss = 488415.44440399
Iteration 952, loss = 488162.91717632
Iteration 953, loss = 487966.46083083
Iteration 954, loss = 487740.77238631
Iteration 955, loss = 487524.68925523
Iteration 956, loss = 487336.52022300
Iteration 957, loss = 487162.74452237
Iteration 958, loss = 486936.18343197
Iteration 959, loss = 486696.81356525
Iteration 960, loss = 486472.04441896
Iteration 961, loss = 486261.19871685
Iteration 962, loss = 486027.38850703
Iteration 963, loss = 485809.20018558
Iteration 964, loss = 485585.00265938
Iteration 965, loss = 485378.02357121
Iteration 966, loss = 485169.56031960
Iteration 967, loss = 484931.80767943
Iteration 968, loss = 484705.65621112
Iteration 969, loss = 484478.66682822
Iteration 970, loss = 484257.96742989
Iteration 971, loss = 484027.99125360
Iteration 972, loss = 483811.93400900
Iteration 973, loss = 483570.05646206
Iteration 974, loss = 483337.40671244
Iteration 975, loss = 483106.74763968
Iteration 97

Iteration 1281, loss = 373297.47987735
Iteration 1282, loss = 372828.21637364
Iteration 1283, loss = 372278.42520380
Iteration 1284, loss = 371783.98789877
Iteration 1285, loss = 371314.23809402
Iteration 1286, loss = 370782.49616609
Iteration 1287, loss = 370284.14825743
Iteration 1288, loss = 369829.66529168
Iteration 1289, loss = 369302.66480886
Iteration 1290, loss = 368804.40483414
Iteration 1291, loss = 368355.21893995
Iteration 1292, loss = 367862.74558291
Iteration 1293, loss = 367366.91933325
Iteration 1294, loss = 366947.36688061
Iteration 1295, loss = 366447.07045405
Iteration 1296, loss = 365987.53985925
Iteration 1297, loss = 365545.03883583
Iteration 1298, loss = 365064.66846494
Iteration 1299, loss = 364619.20080503
Iteration 1300, loss = 364161.53108953
Iteration 1301, loss = 363719.28421309
Iteration 1302, loss = 363266.85036817
Iteration 1303, loss = 362822.15069648
Iteration 1304, loss = 362376.64246224
Iteration 1305, loss = 361925.51484341
Iteration 1306, loss = 36

Iteration 1605, loss = 202467.23977126
Iteration 1606, loss = 201866.46733285
Iteration 1607, loss = 201268.15646800
Iteration 1608, loss = 200674.63030546
Iteration 1609, loss = 200079.03479506
Iteration 1610, loss = 199474.24871064
Iteration 1611, loss = 198875.70023824
Iteration 1612, loss = 198283.57947956
Iteration 1613, loss = 197696.57999677
Iteration 1614, loss = 197103.30191995
Iteration 1615, loss = 196505.20425569
Iteration 1616, loss = 195906.99126697
Iteration 1617, loss = 195311.43520335
Iteration 1618, loss = 194717.21613921
Iteration 1619, loss = 194127.47099146
Iteration 1620, loss = 193539.07211186
Iteration 1621, loss = 192953.06275864
Iteration 1622, loss = 192373.25328515
Iteration 1623, loss = 191799.29256130
Iteration 1624, loss = 191224.46470492
Iteration 1625, loss = 190669.94445356
Iteration 1626, loss = 190091.08735421
Iteration 1627, loss = 189514.97874083
Iteration 1628, loss = 188908.45226762
Iteration 1629, loss = 188302.78171532
Iteration 1630, loss = 18

Iteration 1876, loss = 83682.02149367
Iteration 1877, loss = 83378.89661943
Iteration 1878, loss = 83076.25164016
Iteration 1879, loss = 82774.50969498
Iteration 1880, loss = 82473.79687957
Iteration 1881, loss = 82174.18061458
Iteration 1882, loss = 81875.31216366
Iteration 1883, loss = 81577.00315591
Iteration 1884, loss = 81279.39414046
Iteration 1885, loss = 80982.73470768
Iteration 1886, loss = 80686.96528319
Iteration 1887, loss = 80392.09361872
Iteration 1888, loss = 80098.16521223
Iteration 1889, loss = 79805.15544325
Iteration 1890, loss = 79513.00857538
Iteration 1891, loss = 79221.61196843
Iteration 1892, loss = 78930.89101646
Iteration 1893, loss = 78640.80790385
Iteration 1894, loss = 78351.50736986
Iteration 1895, loss = 78062.95943370
Iteration 1896, loss = 77776.13226618
Iteration 1897, loss = 77490.41684018
Iteration 1898, loss = 77205.61646551
Iteration 1899, loss = 76921.74103937
Iteration 1900, loss = 76638.74313065
Iteration 1901, loss = 76357.10170223
Iteration 19

Iteration 2128, loss = 31053.90002399
Iteration 2129, loss = 30909.06109320
Iteration 2130, loss = 30758.88082340
Iteration 2131, loss = 30631.15642925
Iteration 2132, loss = 30516.23948412
Iteration 2133, loss = 30388.50404926
Iteration 2134, loss = 30246.71633479
Iteration 2135, loss = 30110.69316309
Iteration 2136, loss = 29989.03983075
Iteration 2137, loss = 29869.45209345
Iteration 2138, loss = 29740.10571243
Iteration 2139, loss = 29605.38782503
Iteration 2140, loss = 29476.24155525
Iteration 2141, loss = 29355.14948875
Iteration 2142, loss = 29234.09509147
Iteration 2143, loss = 29107.25095754
Iteration 2144, loss = 28978.17591595
Iteration 2145, loss = 28853.14226159
Iteration 2146, loss = 28732.57346433
Iteration 2147, loss = 28612.10889675
Iteration 2148, loss = 28488.91701962
Iteration 2149, loss = 28364.39395756
Iteration 2150, loss = 28241.64178963
Iteration 2151, loss = 28121.73013220
Iteration 2152, loss = 28002.79368270
Iteration 2153, loss = 27882.89759259
Iteration 21

Iteration 2430, loss = 8319.22066151
Iteration 2431, loss = 8388.58461097
Iteration 2432, loss = 8492.98093761
Iteration 2433, loss = 8453.05752776
Iteration 2434, loss = 8275.79699033
Iteration 2435, loss = 8145.72438122
Iteration 2436, loss = 8153.11906861
Iteration 2437, loss = 8208.29988057
Iteration 2438, loss = 8184.73070009
Iteration 2439, loss = 8071.31213299
Iteration 2440, loss = 7974.96682717
Iteration 2441, loss = 7960.20900577
Iteration 2442, loss = 7981.01392222
Iteration 2443, loss = 7958.19251080
Iteration 2444, loss = 7879.59801384
Iteration 2445, loss = 7806.76313370
Iteration 2446, loss = 7783.03824687
Iteration 2447, loss = 7784.03090986
Iteration 2448, loss = 7760.06113480
Iteration 2449, loss = 7700.83243485
Iteration 2450, loss = 7642.74593406
Iteration 2451, loss = 7613.08433265
Iteration 2452, loss = 7600.53654758
Iteration 2453, loss = 7576.12931291
Iteration 2454, loss = 7530.69158635
Iteration 2455, loss = 7482.59786960
Iteration 2456, loss = 7449.60374551
I

In [16]:
#Convertim datele din float in int
result_int = []
for x in y_pred:
    result_int.append(x.astype(int))

result_int

[array([-10,   5,   0,   0]),
 array([-11,   4,  -1,   0]),
 array([11512,   651,   400,    25]),
 array([6534,  336,  312,   19]),
 array([-7,  5,  0,  0]),
 array([35,  5, 19,  0]),
 array([5289,  257,  290,   17]),
 array([314, -22,  86,   0]),
 array([26,  5, 15,  0]),
 array([16,  5, 11,  0]),
 array([9645,  533,  367,   23]),
 array([8712,  474,  350,   22]),
 array([4045,  178,  268,   16]),
 array([21,  5, 13,  0]),
 array([-24,   0, -13,   0]),
 array([45,  5, 23,  0]),
 array([5600,  277,  295,   18]),
 array([2, 5, 5, 0]),
 array([23,  5, 14,  0]),
 array([7156,  375,  323,   20]),
 array([14,  5, 11,  0])]

In [17]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

#Folosim diferite scalere pentru a puteam face operatii de normalizare, standardizare si scalare
std_scaler = StandardScaler() 
std_scaler2 = StandardScaler()
minMaxScaler = MinMaxScaler()

In [18]:
minMaxScaler.fit(X_train)  
X_train = minMaxScaler.transform(X_train)  

#Normalizam si scalam setul de train
std_scaler.fit(X_train)  
X_train = std_scaler.transform(X_train) 
std_scaler2.fit(X_train)  
X_train = std_scaler2.transform(X_train) 

In [19]:
#Normalizam si scalam setul de test
minMaxScaler.fit(X_test) 
X_test = minMaxScaler.transform(X_test)  
std_scaler.fit(X_test) 
X_test = std_scaler.transform(X_test)  

In [20]:
#Scalam si standardizam datele de test
std_scaler2.fit(X_test) 
X_test = std_scaler2.transform(X_test)  

In [21]:
#Antrenam modeul folosind setul de train
regr.fit(X_train, y_train)

#Facem predictii
y_pred = regr.predict(X_test)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Iteration 1, loss = 1629182.34781790
Iteration 2, loss = 1629140.54172492
Iteration 3, loss = 1629100.43913662
Iteration 4, loss = 1629063.04530319
Iteration 5, loss = 1629027.61051024
Iteration 6, loss = 1628992.57344482
Iteration 7, loss = 1628958.60501513
Iteration 8, loss = 1628924.73022476
Iteration 9, loss = 1628890.76451871
Iteration 10, loss = 1628856.83331617
Iteration 11, loss = 1628822.79809934
Iteration 12, loss = 1628788.65935587
Iteration 13, loss = 1628755.09967100
Iteration 14, loss = 1628720.68760082
Iteration 15, loss = 1628685.02576842
Iteration 16, loss = 1628648.05195735
Iteration 17, loss = 1628609.68811561
Iteration 18, loss = 1628569.84957521
Iteration 19, loss = 1628528.44927904
Iteration 20, loss = 1628485.82883990
Iteration 21, loss = 1628442.92059232
Iteration 22, loss = 1628398.20160888
Iteration 23, loss = 1628351.58933057
Iteration 24, loss = 1628303.04838297
Iteration 25, loss = 1628253.00711972
Iteration 26, loss = 1628200.84137363
Iteration 27, loss = 

Iteration 306, loss = 1040756.03825872
Iteration 307, loss = 1036070.96942539
Iteration 308, loss = 1031381.84858961
Iteration 309, loss = 1026690.12351587
Iteration 310, loss = 1021993.41374983
Iteration 311, loss = 1017294.23714613
Iteration 312, loss = 1012592.33663566
Iteration 313, loss = 1007886.74201246
Iteration 314, loss = 1003178.23793704
Iteration 315, loss = 998469.11357997
Iteration 316, loss = 993755.55400012
Iteration 317, loss = 989040.08765962
Iteration 318, loss = 984323.62600821
Iteration 319, loss = 979610.29490848
Iteration 320, loss = 974896.52576920
Iteration 321, loss = 970183.35960888
Iteration 322, loss = 965473.02891276
Iteration 323, loss = 960761.53802482
Iteration 324, loss = 956054.19967165
Iteration 325, loss = 951351.24240326
Iteration 326, loss = 946651.56514410
Iteration 327, loss = 941954.26504250
Iteration 328, loss = 937261.17735914
Iteration 329, loss = 932570.03893436
Iteration 330, loss = 927884.01456448
Iteration 331, loss = 923201.38150511
Ite

Iteration 615, loss = 254519.14461291
Iteration 616, loss = 253646.47665396
Iteration 617, loss = 252773.22572530
Iteration 618, loss = 251902.51510024
Iteration 619, loss = 251037.78317008
Iteration 620, loss = 250173.80942204
Iteration 621, loss = 249310.70551519
Iteration 622, loss = 248453.80882563
Iteration 623, loss = 247602.19864970
Iteration 624, loss = 246748.79267708
Iteration 625, loss = 245898.75232964
Iteration 626, loss = 245051.20168947
Iteration 627, loss = 244208.27075871
Iteration 628, loss = 243366.52798206
Iteration 629, loss = 242525.54931447
Iteration 630, loss = 241687.37959640
Iteration 631, loss = 240856.82037142
Iteration 632, loss = 240023.92026513
Iteration 633, loss = 239189.81539326
Iteration 634, loss = 238361.39140481
Iteration 635, loss = 237539.27028142
Iteration 636, loss = 236716.02896516
Iteration 637, loss = 235893.47920023
Iteration 638, loss = 235074.53401299
Iteration 639, loss = 234258.95093529
Iteration 640, loss = 233444.45798722
Iteration 64

Iteration 889, loss = 97321.32209820
Iteration 890, loss = 96993.45866633
Iteration 891, loss = 96666.16855203
Iteration 892, loss = 96338.85983510
Iteration 893, loss = 96013.70969370
Iteration 894, loss = 95690.44758861
Iteration 895, loss = 95367.80189682
Iteration 896, loss = 95046.46148570
Iteration 897, loss = 94725.52486310
Iteration 898, loss = 94405.87912073
Iteration 899, loss = 94087.16549996
Iteration 900, loss = 93768.48040944
Iteration 901, loss = 93450.37334285
Iteration 902, loss = 93133.58674799
Iteration 903, loss = 92817.10049436
Iteration 904, loss = 92500.22452725
Iteration 905, loss = 92184.40956812
Iteration 906, loss = 91869.62182308
Iteration 907, loss = 91555.85537613
Iteration 908, loss = 91242.91204853
Iteration 909, loss = 90930.20273250
Iteration 910, loss = 90616.97508850
Iteration 911, loss = 90305.21464489
Iteration 912, loss = 89994.52624135
Iteration 913, loss = 89682.33249396
Iteration 914, loss = 89371.59906995
Iteration 915, loss = 89062.52909763
I

Iteration 1148, loss = 41424.39384629
Iteration 1149, loss = 41296.23631641
Iteration 1150, loss = 41168.45876207
Iteration 1151, loss = 41041.03096206
Iteration 1152, loss = 40913.90900753
Iteration 1153, loss = 40787.14342256
Iteration 1154, loss = 40660.51949835
Iteration 1155, loss = 40534.24057670
Iteration 1156, loss = 40408.23025954
Iteration 1157, loss = 40282.53425347
Iteration 1158, loss = 40157.17481241
Iteration 1159, loss = 40032.21359295
Iteration 1160, loss = 39907.60786182
Iteration 1161, loss = 39783.37516067
Iteration 1162, loss = 39659.41844361
Iteration 1163, loss = 39535.71771779
Iteration 1164, loss = 39412.41225437
Iteration 1165, loss = 39289.29455173
Iteration 1166, loss = 39166.53465448
Iteration 1167, loss = 39044.16227442
Iteration 1168, loss = 38922.15374256
Iteration 1169, loss = 38800.51232698
Iteration 1170, loss = 38679.47214186
Iteration 1171, loss = 38559.45708074
Iteration 1172, loss = 38440.05829306
Iteration 1173, loss = 38321.51536034
Iteration 11

Iteration 1392, loss = 20420.37442738
Iteration 1393, loss = 20365.46219102
Iteration 1394, loss = 20310.67269866
Iteration 1395, loss = 20256.31441109
Iteration 1396, loss = 20202.32120155
Iteration 1397, loss = 20148.34096373
Iteration 1398, loss = 20094.54874742
Iteration 1399, loss = 20040.93461960
Iteration 1400, loss = 19987.52452598
Iteration 1401, loss = 19934.08087742
Iteration 1402, loss = 19881.00945854
Iteration 1403, loss = 19828.10469232
Iteration 1404, loss = 19775.21547137
Iteration 1405, loss = 19722.23467821
Iteration 1406, loss = 19669.31182683
Iteration 1407, loss = 19616.50173979
Iteration 1408, loss = 19564.03208878
Iteration 1409, loss = 19511.61114507
Iteration 1410, loss = 19459.46722829
Iteration 1411, loss = 19407.37173096
Iteration 1412, loss = 19355.20610457
Iteration 1413, loss = 19303.18450756
Iteration 1414, loss = 19251.48154448
Iteration 1415, loss = 19199.96795451
Iteration 1416, loss = 19148.61916267
Iteration 1417, loss = 19097.20478175
Iteration 14

Iteration 1657, loss = 10517.02850102
Iteration 1658, loss = 10491.95747144
Iteration 1659, loss = 10466.98443047
Iteration 1660, loss = 10442.04887372
Iteration 1661, loss = 10417.26751256
Iteration 1662, loss = 10392.63106480
Iteration 1663, loss = 10368.14779697
Iteration 1664, loss = 10343.86945698
Iteration 1665, loss = 10319.70190785
Iteration 1666, loss = 10295.57477813
Iteration 1667, loss = 10271.42522161
Iteration 1668, loss = 10247.29034944
Iteration 1669, loss = 10223.21503611
Iteration 1670, loss = 10199.23175290
Iteration 1671, loss = 10175.42571665
Iteration 1672, loss = 10151.70628062
Iteration 1673, loss = 10128.02390831
Iteration 1674, loss = 10104.39910352
Iteration 1675, loss = 10080.83524471
Iteration 1676, loss = 10057.43940590
Iteration 1677, loss = 10034.15322377
Iteration 1678, loss = 10010.98794039
Iteration 1679, loss = 9987.91234042
Iteration 1680, loss = 9964.88659004
Iteration 1681, loss = 9941.95138200
Iteration 1682, loss = 9919.11716181
Iteration 1683, 

Iteration 1975, loss = 5086.97041567
Iteration 1976, loss = 5075.21941351
Iteration 1977, loss = 5063.52249903
Iteration 1978, loss = 5051.85248996
Iteration 1979, loss = 5040.19294033
Iteration 1980, loss = 5028.64102469
Iteration 1981, loss = 5017.13619825
Iteration 1982, loss = 5005.61292731
Iteration 1983, loss = 4994.09393004
Iteration 1984, loss = 4982.58561698
Iteration 1985, loss = 4971.14444214
Iteration 1986, loss = 4959.71497668
Iteration 1987, loss = 4948.28203235
Iteration 1988, loss = 4937.00567760
Iteration 1989, loss = 4925.74015622
Iteration 1990, loss = 4914.53627463
Iteration 1991, loss = 4903.34943138
Iteration 1992, loss = 4892.17499850
Iteration 1993, loss = 4881.05096599
Iteration 1994, loss = 4869.97115015
Iteration 1995, loss = 4858.93189154
Iteration 1996, loss = 4847.91562241
Iteration 1997, loss = 4836.94829295
Iteration 1998, loss = 4825.99809288
Iteration 1999, loss = 4815.04847275
Iteration 2000, loss = 4804.09524704
Iteration 2001, loss = 4793.16521930
I

Iteration 2292, loss = 2537.91432523
Iteration 2293, loss = 2532.51989415
Iteration 2294, loss = 2527.14232843
Iteration 2295, loss = 2521.77921462
Iteration 2296, loss = 2516.42593790
Iteration 2297, loss = 2511.08551416
Iteration 2298, loss = 2505.75193115
Iteration 2299, loss = 2500.42906365
Iteration 2300, loss = 2495.11949141
Iteration 2301, loss = 2489.82253241
Iteration 2302, loss = 2484.52805317
Iteration 2303, loss = 2479.23444190
Iteration 2304, loss = 2473.95096450
Iteration 2305, loss = 2468.68011086
Iteration 2306, loss = 2463.41995324
Iteration 2307, loss = 2458.17334956
Iteration 2308, loss = 2452.93805744
Iteration 2309, loss = 2447.71485268
Iteration 2310, loss = 2442.50300378
Iteration 2311, loss = 2437.30205740
Iteration 2312, loss = 2432.11585993
Iteration 2313, loss = 2426.94310567
Iteration 2314, loss = 2421.78466575
Iteration 2315, loss = 2416.63712656
Iteration 2316, loss = 2411.50519598
Iteration 2317, loss = 2406.38640028
Iteration 2318, loss = 2401.28145353
I

Iteration 2627, loss = 1293.67100733
Iteration 2628, loss = 1291.29612749
Iteration 2629, loss = 1288.92940926
Iteration 2630, loss = 1286.56819757
Iteration 2631, loss = 1284.21934642
Iteration 2632, loss = 1281.87782891
Iteration 2633, loss = 1279.54364944
Iteration 2634, loss = 1277.21661483
Iteration 2635, loss = 1274.89667892
Iteration 2636, loss = 1272.58420757
Iteration 2637, loss = 1270.28833085
Iteration 2638, loss = 1267.99282644
Iteration 2639, loss = 1265.70116604
Iteration 2640, loss = 1263.42306089
Iteration 2641, loss = 1261.16074905
Iteration 2642, loss = 1258.90751304
Iteration 2643, loss = 1256.66111831
Iteration 2644, loss = 1254.42196121
Iteration 2645, loss = 1252.19014119
Iteration 2646, loss = 1249.96767513
Iteration 2647, loss = 1247.75110827
Iteration 2648, loss = 1245.54277066
Iteration 2649, loss = 1243.34397440
Iteration 2650, loss = 1241.15154002
Iteration 2651, loss = 1238.96603724
Iteration 2652, loss = 1236.78652390
Iteration 2653, loss = 1234.61448367
I

Iteration 2967, loss = 759.74581969
Iteration 2968, loss = 758.83953827
Iteration 2969, loss = 757.93280913
Iteration 2970, loss = 757.03116392
Iteration 2971, loss = 756.13321424
Iteration 2972, loss = 755.23393464
Iteration 2973, loss = 754.33991520
Iteration 2974, loss = 753.44856303
Iteration 2975, loss = 752.55810058
Iteration 2976, loss = 751.67311127
Iteration 2977, loss = 750.78978781
Iteration 2978, loss = 749.90861184
Iteration 2979, loss = 749.03146544
Iteration 2980, loss = 748.15535695
Iteration 2981, loss = 747.28208598
Iteration 2982, loss = 746.40859950
Iteration 2983, loss = 745.54225514
Iteration 2984, loss = 744.67740111
Iteration 2985, loss = 743.81246384
Iteration 2986, loss = 742.95358763
Iteration 2987, loss = 742.09565224
Iteration 2988, loss = 741.23860810
Iteration 2989, loss = 740.39218297
Iteration 2990, loss = 739.54048956
Iteration 2991, loss = 738.69216997
Iteration 2992, loss = 737.85076072
Iteration 2993, loss = 737.00976099
Iteration 2994, loss = 736.1

Iteration 3280, loss = 566.49236050
Iteration 3281, loss = 566.10684567
Iteration 3282, loss = 565.72022789
Iteration 3283, loss = 565.33807358
Iteration 3284, loss = 564.95962445
Iteration 3285, loss = 564.57804853
Iteration 3286, loss = 564.19849065
Iteration 3287, loss = 563.81971141
Iteration 3288, loss = 563.44186573
Iteration 3289, loss = 563.06746269
Iteration 3290, loss = 562.69351453
Iteration 3291, loss = 562.31452437
Iteration 3292, loss = 561.93861352
Iteration 3293, loss = 561.56798390
Iteration 3294, loss = 561.19503238
Iteration 3295, loss = 560.82432127
Iteration 3296, loss = 560.45412075
Iteration 3297, loss = 560.08714495
Iteration 3298, loss = 559.72222247
Iteration 3299, loss = 559.36054501
Iteration 3300, loss = 558.99734972
Iteration 3301, loss = 558.63305971
Iteration 3302, loss = 558.26959358
Iteration 3303, loss = 557.90735715
Iteration 3304, loss = 557.54348670
Iteration 3305, loss = 557.18919231
Iteration 3306, loss = 556.83578509
Iteration 3307, loss = 556.4

Iteration 3623, loss = 474.49963060
Iteration 3624, loss = 474.33437761
Iteration 3625, loss = 474.17063982
Iteration 3626, loss = 474.00387035
Iteration 3627, loss = 473.84068682
Iteration 3628, loss = 473.68075474
Iteration 3629, loss = 473.51834569
Iteration 3630, loss = 473.35697736
Iteration 3631, loss = 473.19366574
Iteration 3632, loss = 473.03242250
Iteration 3633, loss = 472.87005355
Iteration 3634, loss = 472.70991252
Iteration 3635, loss = 472.54949182
Iteration 3636, loss = 472.38780860
Iteration 3637, loss = 472.22958606
Iteration 3638, loss = 472.06643627
Iteration 3639, loss = 471.90412062
Iteration 3640, loss = 471.74389785
Iteration 3641, loss = 471.58336443
Iteration 3642, loss = 471.42348339
Iteration 3643, loss = 471.26808108
Iteration 3644, loss = 471.11179152
Iteration 3645, loss = 470.95132953
Iteration 3646, loss = 470.79220175
Iteration 3647, loss = 470.63170400
Iteration 3648, loss = 470.47673733
Iteration 3649, loss = 470.32213865
Iteration 3650, loss = 470.1

Iteration 3961, loss = 440.12710802
Iteration 3962, loss = 440.07104865
Iteration 3963, loss = 440.01375607
Iteration 3964, loss = 439.95852216
Iteration 3965, loss = 439.90261284
Iteration 3966, loss = 439.84754104
Iteration 3967, loss = 439.79240353
Iteration 3968, loss = 439.73744832
Iteration 3969, loss = 439.68269020
Iteration 3970, loss = 439.62790756
Iteration 3971, loss = 439.57254146
Iteration 3972, loss = 439.51814797
Iteration 3973, loss = 439.46560035
Iteration 3974, loss = 439.41106422
Iteration 3975, loss = 439.35596476
Iteration 3976, loss = 439.30250502
Iteration 3977, loss = 439.24870493
Iteration 3978, loss = 439.19379554
Iteration 3979, loss = 439.14109271
Iteration 3980, loss = 439.08829744
Iteration 3981, loss = 439.03465194
Iteration 3982, loss = 438.98177016
Iteration 3983, loss = 438.92849458
Iteration 3984, loss = 438.87627219
Iteration 3985, loss = 438.82355635
Iteration 3986, loss = 438.77101535
Iteration 3987, loss = 438.71908333
Iteration 3988, loss = 438.6

Iteration 4303, loss = 426.90600620
Iteration 4304, loss = 426.87611483
Iteration 4305, loss = 426.84546935
Iteration 4306, loss = 426.81276320
Iteration 4307, loss = 426.78186368
Iteration 4308, loss = 426.75699004
Iteration 4309, loss = 426.72586748
Iteration 4310, loss = 426.69435855
Iteration 4311, loss = 426.66615974
Iteration 4312, loss = 426.63760530
Iteration 4313, loss = 426.60990469
Iteration 4314, loss = 426.58033813
Iteration 4315, loss = 426.55175052
Iteration 4316, loss = 426.52347198
Iteration 4317, loss = 426.49253837
Iteration 4318, loss = 426.46364778
Iteration 4319, loss = 426.43436657
Iteration 4320, loss = 426.40532243
Iteration 4321, loss = 426.37870646
Iteration 4322, loss = 426.35122168
Iteration 4323, loss = 426.32193838
Iteration 4324, loss = 426.29143717
Iteration 4325, loss = 426.26293238
Iteration 4326, loss = 426.23458064
Iteration 4327, loss = 426.20758349
Iteration 4328, loss = 426.17875158
Iteration 4329, loss = 426.15210398
Iteration 4330, loss = 426.1

Iteration 4639, loss = 419.49654584
Iteration 4640, loss = 419.48031794
Iteration 4641, loss = 419.46322444
Iteration 4642, loss = 419.44618551
Iteration 4643, loss = 419.42825057
Iteration 4644, loss = 419.41344190
Iteration 4645, loss = 419.39855189
Iteration 4646, loss = 419.38220935
Iteration 4647, loss = 419.36649943
Iteration 4648, loss = 419.35268205
Iteration 4649, loss = 419.33629048
Iteration 4650, loss = 419.31952478
Iteration 4651, loss = 419.30555414
Iteration 4652, loss = 419.28967468
Iteration 4653, loss = 419.27399559
Iteration 4654, loss = 419.25791162
Iteration 4655, loss = 419.24215714
Iteration 4656, loss = 419.22592782
Iteration 4657, loss = 419.21113742
Iteration 4658, loss = 419.19941428
Iteration 4659, loss = 419.18352891
Iteration 4660, loss = 419.16526837
Iteration 4661, loss = 419.15061595
Iteration 4662, loss = 419.13600350
Iteration 4663, loss = 419.12002302
Iteration 4664, loss = 419.10760681
Iteration 4665, loss = 419.09189319
Iteration 4666, loss = 419.0

Iteration 4977, loss = 415.65458171
Iteration 4978, loss = 415.64126297
Iteration 4979, loss = 415.63287422
Iteration 4980, loss = 415.62514117
Iteration 4981, loss = 415.61846472
Iteration 4982, loss = 415.60658810
Iteration 4983, loss = 415.59850182
Iteration 4984, loss = 415.59037832
Iteration 4985, loss = 415.58286169
Iteration 4986, loss = 415.57371377
Iteration 4987, loss = 415.57008548
Iteration 4988, loss = 415.56101617
Iteration 4989, loss = 415.54965084
Iteration 4990, loss = 415.53764894
Iteration 4991, loss = 415.53004718
Iteration 4992, loss = 415.52525346
Iteration 4993, loss = 415.51440854
Iteration 4994, loss = 415.50467185
Iteration 4995, loss = 415.49657377
Iteration 4996, loss = 415.48871651
Iteration 4997, loss = 415.48178909
Iteration 4998, loss = 415.47454468
Iteration 4999, loss = 415.46332378
Iteration 5000, loss = 415.45551782
Iteration 5001, loss = 415.44798317
Iteration 5002, loss = 415.44085362
Iteration 5003, loss = 415.43560877
Iteration 5004, loss = 415.4

Iteration 5311, loss = 413.22932602
Iteration 5312, loss = 413.21979819
Iteration 5313, loss = 413.21298998
Iteration 5314, loss = 413.20634432
Iteration 5315, loss = 413.19873261
Iteration 5316, loss = 413.19066080
Iteration 5317, loss = 413.18890331
Iteration 5318, loss = 413.18260606
Iteration 5319, loss = 413.17761718
Iteration 5320, loss = 413.16925325
Iteration 5321, loss = 413.16394014
Iteration 5322, loss = 413.15547284
Iteration 5323, loss = 413.15000028
Iteration 5324, loss = 413.14484613
Iteration 5325, loss = 413.13881072
Iteration 5326, loss = 413.13241314
Iteration 5327, loss = 413.12543517
Iteration 5328, loss = 413.12270741
Iteration 5329, loss = 413.11813238
Iteration 5330, loss = 413.10880191
Iteration 5331, loss = 413.10509023
Iteration 5332, loss = 413.09994869
Iteration 5333, loss = 413.09213270
Iteration 5334, loss = 413.08798513
Iteration 5335, loss = 413.08184389
Iteration 5336, loss = 413.07239677
Iteration 5337, loss = 413.06874433
Iteration 5338, loss = 413.0

Iteration 5593, loss = 411.77481601
Iteration 5594, loss = 411.76390250
Iteration 5595, loss = 411.76292608
Iteration 5596, loss = 411.75798087
Iteration 5597, loss = 411.75375071
Iteration 5598, loss = 411.75480183
Iteration 5599, loss = 411.74699148
Iteration 5600, loss = 411.74002693
Iteration 5601, loss = 411.73755185
Iteration 5602, loss = 411.73237690
Iteration 5603, loss = 411.72211379
Iteration 5604, loss = 411.71567067
Iteration 5605, loss = 411.71314222
Iteration 5606, loss = 411.70994238
Iteration 5607, loss = 411.70564351
Iteration 5608, loss = 411.70177343
Iteration 5609, loss = 411.69583624
Iteration 5610, loss = 411.68731911
Iteration 5611, loss = 411.68958367
Iteration 5612, loss = 411.68645202
Iteration 5613, loss = 411.67884061
Iteration 5614, loss = 411.67539514
Iteration 5615, loss = 411.67012407
Iteration 5616, loss = 411.67251999
Iteration 5617, loss = 411.67216992
Iteration 5618, loss = 411.66764396
Iteration 5619, loss = 411.65564127
Iteration 5620, loss = 411.6

Iteration 5901, loss = 410.62442818
Iteration 5902, loss = 410.61976530
Iteration 5903, loss = 410.61411778
Iteration 5904, loss = 410.61665640
Iteration 5905, loss = 410.61207989
Iteration 5906, loss = 410.60256493
Iteration 5907, loss = 410.60136506
Iteration 5908, loss = 410.59933682
Iteration 5909, loss = 410.59459623
Iteration 5910, loss = 410.59415331
Iteration 5911, loss = 410.58961864
Iteration 5912, loss = 410.59040618
Iteration 5913, loss = 410.58767168
Iteration 5914, loss = 410.58154791
Iteration 5915, loss = 410.57694628
Iteration 5916, loss = 410.57239503
Iteration 5917, loss = 410.56919777
Iteration 5918, loss = 410.55781866
Iteration 5919, loss = 410.55179659
Iteration 5920, loss = 410.54974292
Iteration 5921, loss = 410.54866589
Iteration 5922, loss = 410.54663180
Iteration 5923, loss = 410.54752669
Iteration 5924, loss = 410.54711768
Iteration 5925, loss = 410.54501690
Iteration 5926, loss = 410.54889068
Iteration 5927, loss = 410.54772237
Iteration 5928, loss = 410.5

Iteration 6168, loss = 409.14327351
Iteration 6169, loss = 409.14347594
Iteration 6170, loss = 409.13786997
Iteration 6171, loss = 409.13412757
Iteration 6172, loss = 409.13609972
Iteration 6173, loss = 409.13601003
Iteration 6174, loss = 409.13770489
Iteration 6175, loss = 409.12903522
Iteration 6176, loss = 409.12629120
Iteration 6177, loss = 409.12091249
Iteration 6178, loss = 409.11610335
Iteration 6179, loss = 409.11076693
Iteration 6180, loss = 409.10386079
Iteration 6181, loss = 409.09838976
Iteration 6182, loss = 409.09581976
Iteration 6183, loss = 409.09189225
Iteration 6184, loss = 409.08395415
Iteration 6185, loss = 409.08657389
Iteration 6186, loss = 409.08413957
Iteration 6187, loss = 409.07912367
Iteration 6188, loss = 409.07371409
Iteration 6189, loss = 409.06895122
Iteration 6190, loss = 409.07165954
Iteration 6191, loss = 409.06593557
Iteration 6192, loss = 409.05954277
Iteration 6193, loss = 409.05883488
Iteration 6194, loss = 409.05616010
Iteration 6195, loss = 409.0

Iteration 6458, loss = 408.15014456
Iteration 6459, loss = 408.14746743
Iteration 6460, loss = 408.14207316
Iteration 6461, loss = 408.14326321
Iteration 6462, loss = 408.14658026
Iteration 6463, loss = 408.14271902
Iteration 6464, loss = 408.13550606
Iteration 6465, loss = 408.12948187
Iteration 6466, loss = 408.13055070
Iteration 6467, loss = 408.13113149
Iteration 6468, loss = 408.11869665
Iteration 6469, loss = 408.12049575
Iteration 6470, loss = 408.11792239
Iteration 6471, loss = 408.12030983
Iteration 6472, loss = 408.12128909
Iteration 6473, loss = 408.11651980
Iteration 6474, loss = 408.10946435
Iteration 6475, loss = 408.11351417
Iteration 6476, loss = 408.11869579
Iteration 6477, loss = 408.11107788
Iteration 6478, loss = 408.10343738
Iteration 6479, loss = 408.09913089
Iteration 6480, loss = 408.09296278
Iteration 6481, loss = 408.08292108
Iteration 6482, loss = 408.07185348
Iteration 6483, loss = 408.07158425
Iteration 6484, loss = 408.06849525
Iteration 6485, loss = 408.0

Iteration 6741, loss = 407.08024867
Iteration 6742, loss = 407.07803718
Iteration 6743, loss = 407.07149072
Iteration 6744, loss = 407.07551422
Iteration 6745, loss = 407.06267562
Iteration 6746, loss = 407.05940899
Iteration 6747, loss = 407.05507395
Iteration 6748, loss = 407.04577396
Iteration 6749, loss = 407.06224080
Iteration 6750, loss = 407.05772617
Iteration 6751, loss = 407.05068086
Iteration 6752, loss = 407.04616817
Iteration 6753, loss = 407.04777784
Iteration 6754, loss = 407.04024176
Iteration 6755, loss = 407.02787073
Iteration 6756, loss = 407.01751544
Iteration 6757, loss = 407.03255793
Iteration 6758, loss = 407.02388588
Iteration 6759, loss = 407.01386081
Iteration 6760, loss = 406.99934381
Iteration 6761, loss = 407.00071015
Iteration 6762, loss = 406.99900354
Iteration 6763, loss = 407.00259122
Iteration 6764, loss = 406.99335287
Iteration 6765, loss = 406.99257620
Iteration 6766, loss = 406.98885554
Iteration 6767, loss = 406.98147194
Iteration 6768, loss = 406.9

Iteration 7005, loss = 406.05028027
Iteration 7006, loss = 406.05038793
Iteration 7007, loss = 406.04311442
Iteration 7008, loss = 406.04093865
Iteration 7009, loss = 406.03810874
Iteration 7010, loss = 406.03890136
Iteration 7011, loss = 406.04269991
Iteration 7012, loss = 406.02751365
Iteration 7013, loss = 406.01872062
Iteration 7014, loss = 406.01582221
Iteration 7015, loss = 406.03049700
Iteration 7016, loss = 406.02698877
Iteration 7017, loss = 405.99853466
Iteration 7018, loss = 406.00133529
Iteration 7019, loss = 405.99923689
Iteration 7020, loss = 405.97892199
Iteration 7021, loss = 405.97082432
Iteration 7022, loss = 405.98054452
Iteration 7023, loss = 405.98436076
Iteration 7024, loss = 405.97416374
Iteration 7025, loss = 405.96181981
Iteration 7026, loss = 405.96098081
Iteration 7027, loss = 405.96094046
Iteration 7028, loss = 405.95211246
Iteration 7029, loss = 405.94600139
Iteration 7030, loss = 405.94019123
Iteration 7031, loss = 405.93465198
Iteration 7032, loss = 405.9

Iteration 7281, loss = 405.02304758
Iteration 7282, loss = 405.02492575
Iteration 7283, loss = 405.01764364
Iteration 7284, loss = 405.01205358
Iteration 7285, loss = 405.01030431
Iteration 7286, loss = 405.00744944
Iteration 7287, loss = 404.99717587
Iteration 7288, loss = 404.97890850
Iteration 7289, loss = 404.97338982
Iteration 7290, loss = 404.97251655
Iteration 7291, loss = 404.97524771
Iteration 7292, loss = 404.96240157
Iteration 7293, loss = 404.96303931
Iteration 7294, loss = 404.96335413
Iteration 7295, loss = 404.95998213
Iteration 7296, loss = 404.94886591
Iteration 7297, loss = 404.94727520
Iteration 7298, loss = 404.94112715
Iteration 7299, loss = 404.93412950
Iteration 7300, loss = 404.92826857
Iteration 7301, loss = 404.92781980
Iteration 7302, loss = 404.93971552
Iteration 7303, loss = 404.94330536
Iteration 7304, loss = 404.93404239
Iteration 7305, loss = 404.93324386
Iteration 7306, loss = 404.93656584
Iteration 7307, loss = 404.91478469
Iteration 7308, loss = 404.9

Iteration 7558, loss = 404.26593262
Iteration 7559, loss = 404.26646705
Iteration 7560, loss = 404.25963332
Iteration 7561, loss = 404.26378018
Iteration 7562, loss = 404.26154794
Iteration 7563, loss = 404.24745394
Iteration 7564, loss = 404.24107682
Iteration 7565, loss = 404.23950346
Iteration 7566, loss = 404.24776339
Iteration 7567, loss = 404.24086185
Iteration 7568, loss = 404.23334693
Iteration 7569, loss = 404.22902526
Iteration 7570, loss = 404.22438606
Iteration 7571, loss = 404.23438312
Iteration 7572, loss = 404.23114357
Iteration 7573, loss = 404.22259893
Iteration 7574, loss = 404.21912147
Iteration 7575, loss = 404.20485586
Iteration 7576, loss = 404.20262128
Iteration 7577, loss = 404.20721373
Iteration 7578, loss = 404.21298983
Iteration 7579, loss = 404.20762126
Iteration 7580, loss = 404.19506608
Iteration 7581, loss = 404.19238341
Iteration 7582, loss = 404.19373405
Iteration 7583, loss = 404.18836550
Iteration 7584, loss = 404.17945070
Iteration 7585, loss = 404.1

Iteration 7875, loss = 403.46073152
Iteration 7876, loss = 403.45748864
Iteration 7877, loss = 403.45100694
Iteration 7878, loss = 403.43663697
Iteration 7879, loss = 403.46235801
Iteration 7880, loss = 403.46363271
Iteration 7881, loss = 403.44897747
Iteration 7882, loss = 403.44658578
Iteration 7883, loss = 403.43439541
Iteration 7884, loss = 403.43817815
Iteration 7885, loss = 403.43493146
Iteration 7886, loss = 403.44124583
Iteration 7887, loss = 403.43918657
Iteration 7888, loss = 403.43612183
Iteration 7889, loss = 403.42807251
Iteration 7890, loss = 403.42110712
Iteration 7891, loss = 403.41984571
Iteration 7892, loss = 403.41415955
Iteration 7893, loss = 403.40049334
Iteration 7894, loss = 403.41298160
Iteration 7895, loss = 403.41537277
Iteration 7896, loss = 403.42516782
Iteration 7897, loss = 403.42587142
Iteration 7898, loss = 403.40526321
Iteration 7899, loss = 403.43341236
Iteration 7900, loss = 403.43394827
Iteration 7901, loss = 403.43871940
Iteration 7902, loss = 403.4

In [22]:
#Convertim din float in int
result_int = []
for x in y_pred:
    result_int.append(x.astype(int))

result_int

[array([0, 0, 0, 0]),
 array([0, 0, 0, 0]),
 array([10178,   558,   330,    22]),
 array([3294,  137,  319,   19]),
 array([0, 0, 0, 0]),
 array([ 2,  0, -1,  0]),
 array([1888,   59,  246,   11]),
 array([0, 0, 0, 0]),
 array([0, 0, 0, 0]),
 array([-2,  0,  0,  0]),
 array([7668,  386,  382,   20]),
 array([6330,  309,  368,   20]),
 array([823,  12, 151,   4]),
 array([-1,  0,  0,  0]),
 array([-1,  0,  0,  0]),
 array([-1, -1,  0,  0]),
 array([2198,   76,  264,   13]),
 array([0, 0, 0, 0]),
 array([-1,  0,  0,  0]),
 array([4126,  182,  340,   21]),
 array([-1,  0,  0,  0])]

In [23]:
import warnings
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor

warnings.filterwarnings('ignore')

#MLP Regressor pentru NN Multy Layer
regr = MLPRegressor(solver='adam', hidden_layer_sizes=(200,100), max_iter=10000,activation='relu')
#regr = MLPRegressor(solver=’lbfgs’, hiddenlayersizes=(200,150), maxiter=20000,activation=’relu’, alpha = 0.0003)
#regr = MLPRegressor(solver=’adam’, hiddenlayersizes=(200,100), maxiter=10000,activation=’relu’)

#Cross validation score
cross_val_score(regr, y_test, X_test, cv=4)

array([-1.41007804e+03, -1.32397155e+03, -5.94215491e+02,  7.74466575e-01])

In [24]:
#Pregatim coloana pentru cazuri de persoane infectate
y = data.iloc[:, 2].values
y = y.reshape(-1,1)

X_final = data.iloc[:, 0:2].values

X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.17)

regr.fit(X_train, y_train.ravel())
y_pred = regr.predict(X_test)

y_pred.astype(int)

array([ 6106,    -6,    85,    -7,   -12,     1,  1233,    11,    -5,
         -14,    93,   122,   196,  1449,  7677,   246,     6,   323,
         221, 11679,    17])

In [25]:
y_test

array([[ 5990],
       [    0],
       [   45],
       [    0],
       [    0],
       [    0],
       [ 1029],
       [    3],
       [    0],
       [    0],
       [    0],
       [   89],
       [  184],
       [ 1292],
       [ 7707],
       [  277],
       [    0],
       [  308],
       [    0],
       [11978],
       [    9]])

In [26]:
#daca avem numere negative, le facem 0 pentru a putea aplica metricile de evaluare
num = 0
while(num < len(y_pred)): 
      
    if y_pred[num] < 0: 
        y_pred[num] = 0
    num = num + 1
    
y_pred.astype(int)

array([ 6106,     0,    85,     0,     0,     1,  1233,    11,     0,
           0,    93,   122,   196,  1449,  7677,   246,     6,   323,
         221, 11679,    17])

In [27]:
#Am folosit diferite metrici pentru a putea estima acuritatea rezultatelor obtinute
from sklearn.metrics import explained_variance_score
explained_variance_score(y_test, y_pred)

0.9989264372755813

In [28]:
from sklearn.metrics import max_error
max_error(y_test, y_pred)

298.09753935656954

In [29]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

60.95082109273548

In [30]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

11038.275925048712

In [31]:
from sklearn.metrics import mean_squared_log_error
mean_squared_log_error(y_test, y_pred)

2.7232104926734797

In [32]:
from sklearn.metrics import median_absolute_error
median_absolute_error(y_test, y_pred)

15.534019723698975

In [33]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9988518416658613